### ISSUE TITLE
Bottom Sheet RenderFlex overflow bug 

### ISSUE THREAD

**Issue by HasanAlyazidi** [natintosh/intl_phone_number_input#187]
**Describe the bug**
When keyboard appears while bottom sheet is open. the list of countries becomes hidden and RenderFlex overflow bug occurs.

**Package version**
0.6.0

**Flutter version**
2.0.2

**To Reproduce**
1. Set `SelectorConfig.selectorType` = PhoneInputSelectorType.BOTTOM_SHEET
2. Tap on a flag
3. Focus the search text field

**Expected behavior**
Bottom sheet's countries list should be shown while keyboard is shown.

**Screenshots**
![2021-03-17 17 12 21](https://user-images.githubusercontent.com/7901330/111490761-f5b88000-8743-11eb-9285-2ca2f4154bed.gif)

** Targeted platforms (please complete the following information):**
Tested on android, not sure about iOS and web.

**Additional context**
I tried changing the `locale` and setting `resizeToAvoidBottomInset: false` with no avail.

**Comment by sylvesterasiedu** [comment]
Hello,

I have the same issue on both IOS and android. This happens when I select PhoneInputSelectorType.BOTTOM_SHEET and PhoneInputSelectorType.DROPDOWN

═══════Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while applying parent data.:
Incorrect use of ParentDataWidget.

The ParentDataWidget Expanded(flex: 1) wants to apply ParentData of type FlexParentData to a RenderObject, which has been set up to accept ParentData of incompatible type BoxParentData.

Usually, this means that the Expanded widget has the wrong ancestor RenderObjectWidget. Typically, Expanded widgets are placed directly inside Flex widgets.
The offending Expanded is currently placed inside a Padding widget.

The ownership chain for the RenderObject that received the incompatible parent data was:
  Row ← Container ← _InputWidgetView ← InternationalPhoneNumberInput ← Expanded ← Padding ← Column ← Container ← _FormScope ← WillPopScope ← ⋯
When the exception was thrown, this was the stack
#0      RenderObjectElement._updateParentData.<anonymous closure>
package:flutter/…/widgets/framework.dart:5626
#1      RenderObjectElement._updateParentData
#2      RenderObjectElement.attachRenderObject
package:flutter/…/widgets/framework.dart:5664
#3      RenderObjectElement.mount
package:flutter/…/widgets/framework.dart:5357
#4      MultiChildRenderObjectElement.mount
package:flutter/…/widgets/framework.dart:6090
...

**Comment by natintosh** [comment]
Fixed it. Thanks...

![image](https://user-images.githubusercontent.com/27495055/112542361-c396c600-8db4-11eb-9711-19113e40d234.png)

**Comment by Sathish9222** [comment]
> **Describe the bug**
> When keyboard appears while bottom sheet is open. the list of countries becomes hidden and RenderFlex overflow bug occurs.
> 
> **Package version**
> 0.6.0
> 
> **Flutter version**
> 2.0.2
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Set `SelectorConfig.selectorType` = PhoneInputSelectorType.BOTTOM_SHEET
> 2. Tap on a flag
> 3. Focus the search text field
> 4. See error
> 
> **Expected behavior**
> Bottom sheet's countries list should be shown while keyboard is shown.
> 
> **Screenshots**
> ![2021-03-17 17 12 21](https://user-images.githubusercontent.com/7901330/111490761-f5b88000-8743-11eb-9285-2ca2f4154bed.gif)
> 
> ** Targeted platforms (please complete the following information):**
> Tested on android, not sure about iOS and web.
> 
> **Additional context**
> I tried changing the `locale` and setting `resizeToAvoidBottomInset: false` with no avail.

Hello can you let me know how to change to rtl ?

**Comment by HasanAlyazidi** [comment]
> > **Describe the bug**
> > When keyboard appears while bottom sheet is open. the list of countries becomes hidden and RenderFlex overflow bug occurs.
> > **Package version**
> > 0.6.0
> > **Flutter version**
> > 2.0.2
> > **To Reproduce**
> > Steps to reproduce the behavior:
> > 
> > 1. Set `SelectorConfig.selectorType` = PhoneInputSelectorType.BOTTOM_SHEET
> > 2. Tap on a flag
> > 3. Focus the search text field
> > 4. See error
> > 
> > **Expected behavior**
> > Bottom sheet's countries list should be shown while keyboard is shown.
> > **Screenshots**
> > ![2021-03-17 17 12 21](https://user-images.githubusercontent.com/7901330/111490761-f5b88000-8743-11eb-9285-2ca2f4154bed.gif)
> > ** Targeted platforms (please complete the following information):**
> > Tested on android, not sure about iOS and web.
> > **Additional context**
> > I tried changing the `locale` and setting `resizeToAvoidBottomInset: false` with no avail.
> 
> Hello can you let me know how to change to rtl ?
 
1. Change the locale of your entry point `MaterialApp()` of your app  to a RTL language

2. Set the locale of `InternationalPhoneNumberInput()` to match app's locale

```dart
InternationalPhoneNumberInput(
  locale: 'ar',
  ...
),
```

If the instructions are unclear, tell me and i will show how to do it.
